[package]
name = "ceap"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ceap"
path = "../../quizzes/src/quiz02/c_ceap/src/main.rs"

[dependencies]
trading = { path = "../../libs" }
book = { path = "../../../crypto-n-rust/src/libs/book" }
quizzes = { path = "../../quizzes" }

clap = { version = "4", features = ["derive", "env"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
