[package]
name = "a_gelic"
version = "0.1.0"
edition = "2024"

[dependencies]
book = { path = "../../../../../crypto-n-rust/src/libs/book" }
trading = { path = "../../../../libs" }
quizzes = { path = "../../.." }

clap = { version = "4.6.6", features = ["derive"] }
tokio    = { version = "1.53.1", features = ["macros", "rt-multi-thread"] }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(tarpaulin_include)'] }

[dev-dependencies]
paste = "1"
